spring:
    jpa:
        hibernate:
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    datasource:
        initialize: false
    profiles:
        active: dev

logging:
    config: ./logback.xml
---
spring:
    profiles: dev
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            ddl-auto: validate
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/catalog
        username: root
        password:
        max-active: 10
        initial-size: 5
        autoreconnect: true
        max-idle: 5000
        min-idle: 1
        test-while-idle: true
        test-on-borrow: true
        validation-query: SELECT 1
        time-between-eviction-runs-millis: 5000
        min-evictable-idle-time-millis: 60000
        acquireRetryDelay: 2000
        acquireRetryAttempts: 3